webform.settings.third_party.webform_quiz:
  type: mapping
  label: 'Quiz settings'
  mapping:
    settings:
      type: mapping
      label: 'Quiz settings'
      mapping:
        is_this_a_quiz:
          type: string
          label: 'Is this a quiz?'
        allow_retakes:
          type: boolean
          label: 'Allow retakes?'
        number_of_retakes_allowed:
          type: integer
          label: 'Number of retakes allowed'
